name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore Packages
      run: nuget restore wodat.sln

    - name: Create folder
      run: |
          mkdir -p 'D:/outputrel/outputrel'

    - name: Build solution
      run: msbuild wodat.sln -t:rebuild -property:Configuration=Release -verbosity:diag /p:OutputPath='D:/outputrel/outputrel'
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Release
        path: 'D:/outputrel/outputrel'
